[versions]
mapLibreServices = "6.0.1"
appCompat = "1.7.0"
constraintLayout = "2.1.4"
interpolator = "1.0.0"
recyclerView = "1.3.2"
material = "1.12.0"
uiAutomator = "2.3.0"
espresso = "3.6.1"
testRunner = "1.2.1"
testRules = "1.6.1"
fragment = "1.8.2"
annotation = "1.8.2"
leakCanary = "2.14"
junit = "4.13.2"
mockito = "5.13.0"
mockk = "1.13.12"
robolectric = "4.13"
timber = "5.0.1"
okhttp = "4.12.0"
kotlin = "2.0.20"
licenses = "0.9.8"
lint = "31.6.0"
appcenter = "1.5"
commonsIO = "2.16.1"
assertj = "3.26.3"
gradleNexus = "2.0.0"
multidex = "2.0.1"

androidxTestExtJUnit = "1.1.5"
androidxTestCoreKtx = "1.5.0"
kotlinxSerializationJson = "1.6.0"
kotlinxCoroutines = { strictly = "[1.0, 2.0[" }

androidGradlePlugin = "8.6.0"

[libraries]
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
maplibreJavaGeoJSON = { group = "org.maplibre.gl", name = "android-sdk-geojson", version.ref = "mapLibreServices" }
maplibreGestures = { group = "org.maplibre.gl", name = "maplibre-android-gestures", version = "0.0.3" }
maplibreJavaTurf = { group = "org.maplibre.gl", name = "android-sdk-turf", version.ref = "mapLibreServices" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
assertjcore = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

testRunner = { group = "androidx.test.ext", name = "junit", version.ref = "testRunner" }
testRules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
testEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
testEspressoIntents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
testEspressoContrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
testUiAutomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiAutomator" }
supportAnnotations = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
supportFragmentV4 = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
supportRecyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
supportConstraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
interpolator = { group = "androidx.interpolator", name = "interpolator", version.ref = "interpolator" }
supportDesign = { group = "com.google.android.material", name = "material", version.ref = "material" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

appCenter = { group = "com.microsoft.appcenter", name = "espresso-test-extension", version.ref = "appcenter" }
commonsIO = { group = "commons-io", name = "commons-io", version.ref = "commonsIO" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
leakCanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }

kotlinPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
licensesPlugin = { group = "com.jaredsburrows", name = "gradle-license-plugin", version.ref = "licenses" }

lint = { group = "com.android.tools.lint", name = "lint", version.ref = "lint" }
lintApi = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
lintChecks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "lint" }
lintTests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "lint" }

gradleNexus = { group = "io.github.gradle-nexus", name = "publish-plugin", version.ref = "gradleNexus" }

androidxTestExtJUnit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidxTestCoreKtx = { group = "androidx.test", name = "core-ktx", version = "1.6.1" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.7.2" }

androidGradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin"}


[plugins]
nexusPublishPlugin = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.4.1" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version = "2.0.20" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.0.20" }