name: gh-pages-docc

on:
  workflow_dispatch:

jobs:
  gh-pages-docc:
    defaults:
      run:
        working-directory: platform/ios
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Generate documentation
        run: make ios-docs

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: platform/ios/build/ios/static-docs
          target-folder: docs/ios/docc/
