name: gh-pages-cpp-api

on:
  workflow_dispatch:

jobs:
  generate-and-deploy-gh-pages-cpp-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          submodules: true

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate documentation
        working-directory: docs/doxygen
        run: doxygen

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: gh-pages
          folder: docs/doxygen/html
          target-folder: cpp/api/
