name: gh-pages-cpp-api

on:
  workflow_dispatch:

jobs:
  generate-and-deploy-gh-pages-cpp-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate documentation
        working-directory: docs/doxygen
        run: doxygen

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: docs/doxygen/html
          target-folder: cpp/api/
