name: gh-pages-docc

permissions:
  id-token: write
  pages: write
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - ios-ci
    types:
      - completed

jobs:
  gh-pages-docc-build:
    if: ${{ github.ref_name == 'main' }}
    name: Build DocC Docs
    runs-on: macos-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v4
        with:
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.run_id }}

      - name: Build DocC documentation
        working-directory: .
        run: |
          HOSTING_BASE_PATH="maplibre-native/ios/latest" platform/ios/scripts/docc.sh

      # workaround since colons in filenames are not allowed in artifacts
      # https://github.com/actions/upload-artifact/issues/333
      - name: Create ZIP archive
        run: |
          cd build
          zip -r docs.zip docs/

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: docc-docs
          path: build/docs.zip

  gh-pages-docc-deploy:
    needs: gh-pages-docc-build
    name: Deploy DocC Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Download DocC docs artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v4
        with:
          name: docc-docs
          path: build

      - name: Unzip documentation
        run: |
          cd build
          unzip docs.zip
          rm docs.zip

      - name: Deploy DocC documentation (main) üöÄ
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: build/docs
          target-folder: ios/latest/
