name: gh-pages-mdbook

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/mdbook/**'
  push:
    branches:
      - main
    paths:
      - 'docs/mdbook/**'

jobs:
  gh-pages-mdbook-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 # v2.0.0
      - name: Install Dependencies
        shell: bash
        run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
      - name: Install mdbook-alerts, mdbook-mermaid
        run: cargo install mdbook-alerts mdbook-mermaid
      - name: Build
        working-directory: docs/mdbook
        shell: bash
        run: mdbook build
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: book
          path: docs/mdbook/book/

  gh-pages-mdbook-deploy:
    needs: gh-pages-mdbook-build
    if: github.event_name != 'pull_request'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: Download book
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v4
        with:
          name: book
          path: artifacts/book

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: gh-pages
          folder: artifacts/book
          target-folder: docs/book
