name: gh-pages-cpp-api

on:
  workflow_dispatch:

jobs:
  generate-and-deploy-gh-pages-cpp-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4
        with:
          submodules: true

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate documentation
        working-directory: docs/doxygen
        run: doxygen

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
        with:
          branch: gh-pages
          folder: docs/doxygen/html
          target-folder: cpp/api/
