name: ios-release-cocoapods

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  ios-release-cocoapods:
    defaults:
      run:
        working-directory: platform/ios
    runs-on: macos-14
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4
        with:
          persist-credentials: false

      - name: Release (CocoaPods)
        shell: bash -leo pipefail {0}  # so pod is found
        run: |
          VERSION=${{ github.event.inputs.version }} COCOAPODS_TRUNK_TOKEN=${{ secrets.COCOAPODS_PASSWORD }} pod trunk push MapLibre.podspec
