name: upload-coverage

on:
  workflow_run:
    workflows: [linux-ci]
    types:
      - completed

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ !steps.parent_workflow.outputs.was_skipped_or_cancelled }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
        with:
          sparse-checkout: |
            .github
            .nvmrc
          persist-credentials: false

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v4
        with:
          node-version-file: '.nvmrc'

      - run: npm install

      - name: Get parent workflow result
        id: parent_workflow
        run: node .github/scripts/check-job-skipped.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_RUN_ID: ${{ github.event.workflow_run.id }}
          JOB_NAME: linux-coverage

  upload-coverage:
    needs: pre_job
    if: needs.pre_job.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
        with:
          persist-credentials: false

      - uses: ./.github/actions/download-workflow-run-artifact
        with:
          artifact-name: coverage-report
          expect-files: "_coverage_report.dat"

      - name: Upload coverage report
        if: '!cancelled()'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          override_commit: ${{ github.event.workflow_run.head_sha }}
          override_pr: ${{ github.event.workflow_run.pull_requests[0].number }}
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "_coverage_report.dat"
          fail_ci_if_error: true
          verbose: true
