name: upload-coverage

on:
  workflow_run:
    workflows: [linux-ci]
    types:
      - completed

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ !steps.parent_workflow.outputs.was_skipped_or_cancelled }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          sparse-checkout: |
            .github
            .nvmrc

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v4
        with:
          node-version-file: '.nvmrc'

      - run: npm install

      - name: Get parent workflow result
        id: parent_workflow
        run: node .github/scripts/check-job-skipped.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_RUN_ID: ${{ github.event.workflow_run.id }}
          JOB_NAME: linux-coverage

  upload-coverage:
    needs: pre_job
    if: needs.pre_job.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - uses: ./.github/actions/download-workflow-run-artifact
        with:
          artifact-name: coverage-report
          expect-files: "_coverage_report.dat"

      - name: Upload coverage report
        if: '!cancelled()'
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5
        with:
          override_commit: ${{ github.event.workflow_run.head_sha }}
          override_pr: ${{ github.event.workflow_run.pull_requests[0].number }}
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "_coverage_report.dat"
          fail_ci_if_error: true
          verbose: true
